FROM mxr:base

ENV INST_SCRIPTS=/tmp
ENV SRC_DIR=./ws


ARG PRJ_DIR=${MY_HOME}/projects
ARG INSTALL_PREFIX=/opt/mxr

ARG PRJ_DIR=${MY_HOME}/projects
ENV PRJ_DIR=${PRJ_DIR}

USER root
RUN apt-get update
RUN apt-get install -y libncurses5-dev

USER ${MY_USER}
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash;rosdep update"

USER root

RUN mkdir -p ${INSTALL_PREFIX}/lib  && \ 
    sh -c "echo ${INSTALL_PREFIX}/lib > /etc/ld.so.conf.d/mxr.conf" && \ 
    ldconfig

RUN mkdir -p ${PRJ_DIR}
RUN cd ${PRJ_DIR}/ &&  \
	git clone https://github.com/mx-car/mx-car.git car &&  \
	cd car &&  \
	sed -i 's/git@github.com:/https:\/\/github.com\//g' mrconfig &&  \
	mr -c mrconfig update
	
RUN mkdir ${PRJ_DIR}/car/lib/mx_joystick/build && \
    cd ${PRJ_DIR}/car/lib/mx_joystick/build && \
    cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} ..  && \
    make install  && \
    echo "export MXJoystick_DIR=${INSTALL_PREFIX}/lib" >> ${MY_HOME}/.bashrc
    
RUN mkdir ${PRJ_DIR}/car/lib/mx_objects/build && \
    cd ${PRJ_DIR}/car/lib/mx_objects/build && \
    cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} ..  && \
    make install  && \
    echo "export MXObjects_DIR=${INSTALL_PREFIX}/lib" >> ${MY_HOME}/.bashrc
    
RUN mkdir ${PRJ_DIR}/car/lib/car_com/build && \
    cd ${PRJ_DIR}/car/lib/car_com/build && \
    cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} ..  && \
    make install  && \
    echo "export CarCom_DIR=${INSTALL_PREFIX}/lib" >> ${MY_HOME}/.bashrc
    
RUN chown -R ${MY_USER}:${MY_USER} ${MY_HOME}

ADD ${SRC_DIR}/src/setup_ws.sh   ${INST_SCRIPTS}/setup_ws.sh  
RUN chmod a+x ${INST_SCRIPTS}/setup_ws.sh
USER ${MY_USER}
RUN $INST_SCRIPTS/setup_ws.sh  

    
# clean apt
USER root
RUN rm -rf /var/lib/apt/lists/*
RUN chown -R ${MY_USER}:${MY_USER} ${MY_HOME}

USER ${MY_USER}
WORKDIR ${MY_HOME}
ENV HOME ${MY_HOME}
CMD /bin/bash
